//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace surathardwarewebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public string Id { get; set; }
        public string Member { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string Gstin { get; set; }
        public string c_person1_Name { get; set; }
        public string c_person1_Mob { get; set; }
        public string c_person2_Name { get; set; }
        public string c_person2_Mob { get; set; }
        public string Landline { get; set; }
        public string Birthdate { get; set; }
        public string Anniversary { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Dealing { get; set; }
        public string Trading_Pattern { get; set; }
        public string Service_to_others { get; set; }
        public string Blood { get; set; }
    }
}
