//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace surathardwarewebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Members_Data
    {
        
        public string Membership_Id { get; set; }
        public string Registration_Date { get; set; }
        public string Registered_By { get; set; }
        public string Id_No { get; set; }
        public string Receipt_No { get; set; }
        public string Referral_Id { get; set; }
        public string Referral_Name { get; set; }
        public string Service_To_Others { get; set; }
        public string Trading_Pattern { get; set; }
        public string Firm_Name { get; set; }
        public string Firm_Type { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Gst_No { get; set; }
        public string Landline_Contact_No { get; set; }
        public string Contact_Person1_Name { get; set; }
        public string Contact_Person1_Mobile { get; set; }
        public string Contact_Person2_Name { get; set; }
        public string Contact_Person2_Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Birthdate_Date { get; set; }
        public string Anniversary_Date { get; set; }
        public string Blood_Group { get; set; }
    }
}
