//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace surathardwarewebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Members_Dealing
    {
        
        public string Membership_Id { get; set; }
        public bool Hardware { get; set; }
        public bool Building_Materials { get; set; }
        public bool PVC_Pipes_Fittings { get; set; }
        public bool Plywood { get; set; }
        public bool Kitchen_Accessories { get; set; }
        public bool Tools { get; set; }
        public bool Cement_Steel { get; set; }
        public bool Sanitary { get; set; }
        public bool Paints { get; set; }
        public bool MS_Pipes_Gi_Pipes { get; set; }
        public bool Electricals { get; set; }
    }
}
