//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace surathardwarewebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public string Request_Id { get; set; }
        public string Request_Type { get; set; }
        public string Request_From { get; set; }
        public string Request_To { get; set; }
        public string Request_Date { get; set; }
        public string Request_Status { get; set; }
        public string Service_To_Others { get; set; }
        public string Trading_Pattern { get; set; }
        public string Firm_Name { get; set; }
        public string Firm_Type { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Gst_No { get; set; }
        public string Landline_Contact_No { get; set; }
        public string Contact_Person1_Name { get; set; }
        public string Contact_Person1_Mobile { get; set; }
        public string Contact_Person2_Name { get; set; }
        public string Contact_Person2_Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Birthdate_Date { get; set; }
        public string Anniversary_Date { get; set; }
        public string Blood_Group { get; set; }
    }
}
